INPUT_DATA_FILENAME = "all_downloaded_records.csv"
PROCESSED_RECORDS_FILENAME = "processed_records.csv"
WORD_LIST_FILENAME = "word_list.pkl"
TERM_DOCUMENT_MATRIX_FILENAME = "term_document_matrix.pkl"
VECTORIZER_FILENAME = "vectorizer.pkl"
